### ISSUE TITLE
Error in browser console

### ISSUE THREAD

**Issue by MiguelAngelRL** [Lemoncode/code-paster#74]
The browser console is showing the following error when the trainer page is showed:

*Warning: Received `true` for a non-boolean attribute `read-only`.
If you want to write it to the DOM, pass a string instead: read-only="true" or read-only={value.toString()}.
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by CopyFieldComponent)
    in div (created by CopyFieldComponent)
    in div (created by CopyFieldComponent)
    in CopyFieldComponent (created by HeaderComponent)
    in div (created by HeaderComponent)
    in HeaderComponent (created by TrainerComponent)
    in main (created by TrainerComponent)
    in TrainerComponent (created by TrainerContainer)
    in TrainerContainer (created by TrainerScene)
    in TrainerScene (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by HashRouter)
    in HashRouter (created by RouterComponent)
    in RouterComponent (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    in StylesProvider (created by ThemeProviderComponent)
    in ThemeProvider (created by ThemeProviderComponent)
    in ThemeProviderComponent*

**Comment by mavv-coder** [comment]
Thanks, Miguel. I'll take care of it right away!
